services:
  node_0:
    build: .
    container_name: cohereDB_node_0
    ports:
      - "52000:8080"
    environment:
      - CONFIG_FILE=configs/server0.toml
    networks:
      - cohere_network
    restart: on-failure
    volumes:
      - node_0_data:/data

  node_1:
    build: .
    container_name: cohereDB_node_1
    ports:
      - "52001:8080"
    environment:
      - CONFIG_FILE=configs/server1.toml
    networks:
      - cohere_network
    restart: on-failure
    volumes:
      - node_1_data:/data

  node_2:
    build: .
    container_name: cohereDB_node_2
    ports:
      - "52002:8080"
    environment:
      - CONFIG_FILE=configs/server2.toml
    networks:
      - cohere_network
    restart: on-failure
    volumes:
      - node_2_data:/data

networks:
  cohere_network:
    driver: bridge

volumes:
  node_0_data:
  node_1_data:
  node_2_data:
